// Nico's Site â posts data
// Each post: { type: "image" | "video", src: "path/to/file", caption: "...", style?: "extra inline CSS for media element" }
// New posts go at the BOTTOM of this array (they render in order).

const posts = [
  { type: "image", src: "images/Delphy.jpg", caption: "If you think me wanting the 51% is unreasonable, just remember you're dealing with someone who thinks he can be an UFC fighter if he put his mind to it" },
  { type: "image", src: "images/AspenJessie.jpg", caption: "Eyes too pretty to censor" },
  { type: "image", src: "images/AspenShot.jpg", caption: "FUCK VAIL SUPPORT LOCAL" },
  { type: "image", src: "images/EngParty.jpg", caption: "\"I don't wanna live a thousand years. If I just live through today, that'll be enough.\" -Portgas D. Ace" },
  { type: "image", src: "images/Bund.jpg", caption: "Shanghai. Chrome Hearts. Quick trip. All pleasure. No business..." },
  { type: "image", src: "images/Hong Kong.jpg", caption: "The Hong Kong Special Administrative Region (HKSAR) of China was a blast. Although productive farm meetings were interupted by regional tensions, unfortunately." },
  { type: "video", src: "videos/IMG_6427.mp4", caption: "The media is lying to you, GI. China is the best, GI." },
  { type: "image", src: "images/Cobra.jpg", caption: "RIP KingCobra. I'll pour anything but Sake on your grave if I get the chance to visit it" },
  { type: "image", src: "images/IMG_5547.jpg", caption: "Den Haag local, I get my residency card soon" },
  { type: "video", src: "videos/IMG_4317 (1).mp4", caption: "The Untimely Death of Matt Himself" },
  { type: "image", src: "images/IMG_2952.JPEG", caption: "Pull up in that Aston feelin like I'm James cause we Bondin" },
  { type: "image", src: "images/IMG_3864.jpg", caption: "\"I met Travis Scott!\" \"I met Taylor Swift!\" Me:" },
  { type: "image", src: "images/IMG_3624.jpg", caption: "Spain sucked but these Euro dishes certainly didn't" },
  { type: "image", src: "images/IMG_2881.jpg", caption: "Wassup Beijing?! Wait this is Florida...gross..." },
  { type: "video", src: "videos/nico 2.mp4", caption: "This kid pushes from ivy, out middle, through our connector like a SPEED DEMON! (Had to run it back the day after to the same editor. This site doens't make me any money, it's getting expensive...)" },
  { type: "video", src: "videos/cs nico.mp4", caption: "I hop on every couple months to see if I still got it (it's like riding a bike). Told the Fiverr editor to do whatever he wanted, not the first time I've been ego checked, and not the last time." },
  { type: "video", src: "videos/Shoehei.mp4", caption: "No one can bring together two races like Shohei Ohtani" },
  { type: "image", src: "images/Security.JPG", caption: "Was it security? Were they protecting an idol in the box? All I know is I feel like the idol (who doesn't need protection)" },
  { type: "image", src: "images/DinnerInKorea.jpg", caption: "Quick dinner in the South, strictly business, no pleasure." },
  { type: "video", src: "videos/DeltaOne.mp4", caption: "Delta One Suite Life on Deck, see you in Korea lmao" },
  { type: "video", src: "videos/IMG_1873.mp4", caption: "I can fix all those lies. Oh, baby, babe, I run, love, I'm running to you. You won't see me cry, I'm hiding inside. My heart is in pain, but I'm smiling for you. Oh, baby, I'll try to make things right. I need you more than air when I'm not with you. Please don't ask me why, just kiss me this time. My only dream is about you and I" },
  { type: "image", src: "images/FruitLogistica.jpg", caption: "No free advertising on this website sorry guys" },
  { type: "image", src: "images/temp_image_7A8071A9-EE8A-42F2-9FDD-21CD3465F11A.jpeg", caption: "The number on the jersey is the dope price" },
  { type: "image", src: "images/IMG_1433.jpeg", caption: "Thought I brought Taylor Gang to Amsterdam but forgot that shit is worldwide" },
  { type: "image", src: "images/IMG_1313.jpeg", caption: "Spent like 10 hours on this flight man, told the pilot ain't no flight plans (seat 56G)" },
  { type: "image", src: "images/Strike.jpg", caption: "BLURRED FOR MY PROTECTION", style: "width: 474px; height: 738px; object-fit: cover;" },
  { type: "image", src: "images/KBBQ.jpg", caption: "Korean bbq in Japan is like BÃÂ¡nh MÃÂ¬ in Thailand" },
  { type: "video", src: "videos/IMG_0883.mov", caption: "Jessie and Paula sitting in a tree, K-I-S-S-I-N-G" },
  { type: "image", src: "images/IMG_0699.jpg", caption: "Sunset=Detroit office    Mucci=Tailgate    Nature Fresh=The Tin Roof" },
  { type: "image", src: "images/ShinOkuboStation.jpg", caption: "Ã£ÂÂ¯Ã£ÂÂ¤Ã£ÂÂÃ£ÂÂ­Ã£ÂÂ¸Ã£ÂÂ¼Ã£ÂÂ®Ã¥Â¤ÂÃ£ÂÂ«Ã£ÂÂ©Ã£ÂÂ³Ã£ÂÂÃ£ÂÂ«Ã£ÂÂ®Ã£ÂÂ¼Ã£ÂÂÃ£ÂÂÃ©Â§ÂÃ¨Â»ÂÃ£ÂÂÃ§Â¶ÂÃ£ÂÂÃ£ÂÂ¦Ã£ÂÂÃ£ÂÂÃ£ÂÂÃ£ÂÂÃ£ÂÂÃ§Â§ÂÃ£ÂÂ¯Ã¦ÂÂ±Ã¤ÂºÂ¬Ã£ÂÂ«Ã£ÂÂÃ£ÂÂÃ£ÂÂÃ£ÂÂ" },
  { type: "image", src: "images/TokyoFit.jpg", caption: "ARTGANGMONEY" },
  { type: "image", src: "images/YNMuseum.jpg", caption: "First yn appreciating Chinese scriptures" },
  { type: "video", src: "videos/IMG_0005.mp4", caption: "I remember my first beer" },
  { type: "video", src: "videos/NoShirt.mp4", caption: "Blud must have gotten into the yerk stash" },
  { type: "image", src: "images/MountainOnPlane.jpg", caption: "Alex says I'm a shit photographer yeah right buddy" },
  { type: "image", src: "images/PaulAndTom.jpg", caption: "Blessed to have two produce visionaries in my life" },
  { type: "image", src: "images/AmsBoat.jpg", caption: "Cruisin Amsterdam's canals with Nike Dunks and Adidas socks" },
  { type: "image", src: "images/RonCostco.jpg", caption: "Ron is the man (Kevin took the pic of us lmao)" },
  { type: "image", src: "images/JessieAsianFood.jpg", caption: "Jessie is the only person in the world who orders sweet potato fries at an Asian restaurant" },
  { type: "image", src: "images/IMG_1479.jpeg", caption: "Updated lads pic before Sammy makes his university debut" },
  { type: "image", src: "images/HorseRacing.jpg", caption: "This day was so much fun I totally get why people lose their families over this" },
  { type: "image", src: "images/IMG_9139.jpeg", caption: "Hogs day 1 with Carlo was a blast" },
  { type: "image", src: "images/VegasSuit.jpg", caption: "If you see me wearing a suit without forces it isn't me" },
  { type: "image", src: "images/PoolsideC.jpg", caption: "This guy chills harder than you if you were on a p30" },
  { type: "image", src: "images/VegasGlasses.jpg", caption: "Aunts glasses, uncles plane, my own swag" },
  { type: "image", src: "images/JessieMyBirthday.jpg", caption: "Taco Scoreboard: Nico-12 Jessie-1/2" },
  { type: "image", src: "images/Amsterdam.jpg", caption: "Germany deserved 0 pictures so here is the connection airport" },
  { type: "image", src: "images/JessiePretendingToBeMe.jpg", caption: "Guys Jessie said I look like this when playing games is that true??" },
  { type: "image", src: "images/JapanAlone.jpg", caption: "I live like the rich and famous when I'm broke and nameless" },
  { type: "image", src: "images/NoCap.PNG", caption: "If you can't count your business casual outfits on one hand keep your distance or I'll create some" },
  { type: "image", src: "images/MichiganNico.jpg", caption: "No flags but hittin from behind (find me on the field)" },
  { type: "image", src: "images/KidRockUs.jpg", caption: "Kid Rock is an asshole, but I didn't expect him to be nice to begin with" },
  { type: "image", src: "images/JessiePI.jpg", caption: "Stop looking at my girlfriend" },
  { type: "video", src: "videos/WizConcert.mp4", caption: "Hold up they don't know my name? Chevy WHO CHEVY WHO" },
  { type: "image", src: "images/A12KobeBeef.jpg", caption: "Imagine Luffy had Kobe beef instead of Sea King meat" },
  { type: "image", src: "images/NicoAndAlexJap.jpg", caption: "Nico got wings Nico got everythinggg" },
  { type: "video", src: "videos/SKYLINE.mp4", caption: "On top of the world and your mom, what's next?" },
  { type: "image", src: "images/BENTLY.jpg", caption: "White on white Bently, big ol black .9 I clap yo monkey ass yeah black on black crime" },
  { type: "image", src: "images/ZoroLost.jpg", caption: "I'm not lost, the map is just wrong" },
  { type: "image", src: "images/WelcomeToTheClub.jpg", caption: "Not the type of auditing I'm used to" },
  { type: "image", src: "images/Nico and Jessie Casino.JPG.jpg", caption: "No Stones but we Rollin" },
  { type: "image", src: "images/AlexOnPJ.JPG", caption: "Pre-nap before the smoke show (45-23)" },
  { type: "image", src: "images/ArubaGear2.JPG", caption: "2nd gear" },
  { type: "image", src: "images/ArubaPete.JPG", caption: "Absolutely fuck this guy on the right of us (not blacking out the face cause I want everyone to know I don't fuck with him), but this was the only good pic of the boys in Aruba together :/" },
  { type: "image", src: "images/CaesarAndCrocs.JPG", caption: "Ruff Rider" },
  { type: "image", src: "images/JessieAtCasino.PNG", caption: "Sugar momma gonna make me a househusband kinda girl" },
  { type: "image", src: "images/LicensePlate.JPG", caption: "She calls my phone up but I told her I'm a loner" },
  { type: "image", src: "images/NicoAlex4Wheeler.JPG", caption: "12 o'clock boys" },
  { type: "image", src: "images/NicoAlexBenz.JPG", caption: "She like my watch, my droptop and my persona" },
  { type: "image", src: "images/NicoAndLittleAlex.PNG", caption: "Lil man big weener" },
  { type: "image", src: "images/NicoWithBunz.JPG", caption: "Space bunz honey bunz" },
  { type: "video", src: "videos/SocialClubBagWithPJ.MP4", caption: "Small plane big turbulence" },
  { type: "video", src: "videos/Yo.mp4", caption: "Yo!." },
  { type: "image", src: "images/IMG_2363.jpeg", caption: "I make it look easy" },
];
